
import streamlit as st


def format_summary_for_download(record):
    """Formats proposal record and rule-based AI brief into a clean text download string."""
    organization_name = st.session_state.get(
        "subscribed_organization_name",
        "Enterprise Proposal Intake Portal",
    )
    return f"""==================================================
{organization_name} EXECUTIVE PROPOSAL BRIEF & SUMMARY
==================================================
Date Submitted  : {record.get('created_at', 'N/A')}
Company Name    : {record.get('company_name', 'N/A')}
CAC RC Number   : {record.get('company_rc', 'N/A')}
Budget / Amount : {record.get('budget', 'N/A')}
Project Timeline: {record.get('timeline', 'N/A')}
Feasibility     : {record.get('feasibility_score', 'N/A')}
Status          : {record.get('status', 'Pending Review')}
--------------------------------------------------
EXECUTIVE SUMMARY PREVIEW:
--------------------------------------------------
{record.get('summary', 'No summary available.')}
==================================================
Generated by {organization_name}
"""

from logo_handler import display_large_logo


def render_executive_company_logo(logo_base64: str | None) -> None:
    """Render a vendor's stored company logo prominently for executives."""
    display_large_logo(logo_base64, width=390)
