[postgres]
host = "localhost"
port = 5432
database = "sgwvm_db"
user = "postgres"
password = "admin"

[openai]
api_key = "sk-proj-YOUR_OPENAI_KEY_HERE"

[prembly]
api_key = "YOUR_PREMBLY_API_KEY_HERE"